version: "3.6"
services:
    web:
        image: richarvey/nginx-php-fpm
        depends_on:
            - db
        container_name: nginx
        ports:
            - "9080:80"
        networks:
            - net1
    db:
        image: mysql/mysql-server:5.7
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=KrolKarolK0ral3
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=app
        networks:
            - net1
            - net2
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 9090:80
        networks:
            - net2
    nodejs:
        build: ./nodeapp
        image: nodejs_local
        container_name: node
        ports:
            - "9001:9001"
networks:
    net1:
    net2:
